
<?php
include 'nav.php';

$apikey = "rzp_test_tceqt6zjA48ytA";
?>
<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
<form action="thanku.html" method="POST">
    <script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
        data-amount="100" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
        data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
  // Replace with the order_id generated by you in the backend.
        data-buttontext="Pay with Razorpay"
        data-name="Sparks"
        data-description="helping others"
        data-image="img/logo.png"
        
        data-prefill.name=""
        data-prefill.email=""
        data-theme.color="#F37254"
    ></script>
    <input type="hidden" custom="Hidden Element" name="hidden">
    </form>
    
        <head>
            <style>
                body{
                    
                    background:  url("img/online.webp") ;
                   background-size:cover;
                    background-repeat:no-repeat;
                    
                }
                .razorpay-payment-button{
                    margin: 0;
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    -ms-transform: translate(-50%, -50%);
                    transform: translate(-50%, -50%);   
                    background:green;
                    color:#fff;
                    font-weight:600;
                    padding:16px;
                    border-radius:10px;
                }
          </style>
</head>
<body>

    
</body>
